### PR TITLE
[Enhancement] Creating env solving using conda with endpoint for it

### LINKED ISSUE #32: Possible env solving
I'm creating this issue to track the development of a new feature for this api: The possibility of providing yml or package names and check if this env is solvable or not.

There are 2 ways to implement that: 
1. via API call for [Conda/Mamba api](https://mamba.readthedocs.io/en/latest/python_api.html)
2. via `conda env create` and wait if the env cand be solved.

If you use conda to solve the environment it'll indirectly try to solve the env using the API.

In my opinion, I'll be faster to deploy using `conda/mamba env create` but it'll fail on performance, as directly calling the api seems to be more reliable and faster.

### PR DESCRIPTION
**Pull request by Mxrcon**
# Creating env solving using conda with endpoint for it

This pull-requests adds a new endpoint named `Solve` which add a conda env recipe solving utility, receiving a recipe yml file and returning only true or false, regarding if it's possible to solve the environment.

Additions: 
- Tests for Solve core login and Solve endpoint
- open api specifications for the new endpoint

Fell free to test the endpoint, the usage is pretty simple: 

```terminal
curl http://localhost:8085/v1/solve -F recipe=@"$TestDataPath/valid.yml"
```

This PR closes #32 and propaby prepare this to the v1.0.0 release :rocket: 

the next goal is to just consume our endpoints using Pode.Web

### CODE REVIEW

**Comment by abhi18av** [comment]
Great idea regarding the addition of the `test-data` 🎉

**Comment by abhi18av** [comment]
@Mxrcon , try to deploy this using fly.io (https://app.clickup.com/t/2wb3y25 ) and let's test this.

**Comment by Mxrcon** [comment]
@abhi18av Sure, Just took some time to test it, and found some interesting values specifically for setting up volumes and a reliable file system to use as work dir for the api. 

More complex stuff when working with docker as well as dockerized apps.

This was the latest command that I used to run the container:
```
docker volume create sucuri-vol
docker run -p 127.0.0.1:8080:8085 --mount source=sucuri-vol,target=/home/sucuri-WorkDir sucuri-api:latest 
```
I was trying to test if it's possible to work with volumes and with the container.

I could make it run when attaching volumes to `/home/sucuri-WorkDir`. 

But I couldn't attach volumes to different paths and then set the `$WORK_DIR` variable pointin to those paths and keep it working.

Honestly, I don't have a lot of time to test it on fly.io right now, perhaps on next week, what do you think?

**Comment by abhi18av** [comment]
> Honestly, I don't have a lot of time to test it on fly.io right now, perhaps on next week, what do you think?

Sure Davi, nothing to worry about. This project would be a priority in 2023 Q1/Q2 and then we can iron out any kind of details. I appreciate the push you've been making and it already simplifies the  effort we'd need to make in 2023 to publish this - great work 👏

**Comment by Mxrcon** [comment]
@abhi18av Thank you for you comprehension, since I could setup and deploy on fly.io without using permanent storage can we merge this? Then I'll circle once I have time to organize the deployment.

**Comment by abhi18av** [comment]
Sure thing - merging ahead now. 🚀 🕺

**Pull request merged**
