### PR TITLE
Updated tests

### PR DESCRIPTION
**Pull request by Aryan-sharma11**
This pull request is regarding tests with updated paths and parameters

### CODE REVIEW

**Comment by Aryan-sharma11** [comment]
> This pull request is regarding tests with updated paths and parameters

@Mxrcon  I have updated the tests according to new path and parameters , right now test for `Fetches latest version with multiple conda channels passed` is getting failed please look into it , and also let me know what more tests we can need to add.

Kindly, Aryan

**Comment by abhi18av** [comment]
@Aryan-sharma11 , thanks for the work on this PR.

> and also let me know what more tests we can need to add.

Perhaps its best if you, as the main author of the project, can share a list of ideas or implement them already.

In general, try to come up with tests for 

- Pure functions
- Code dealing with API responses
- Code dealing with the search of the available (conda/mamba/micromamba) binary

**Comment by Aryan-sharma11** [comment]
> @Aryan-sharma11 , thanks for the work on this PR.
> 
> > and also let me know what more tests we can need to add.
> 
> Perhaps its best if you, as the main author of the project, can share a list of ideas or implement them already.
> 
> In general, try to come up with tests for
> 
> * Pure functions
> * Code dealing with API responses
> * Code dealing with the search of the available (conda/mamba/micromamba) binary

Okay, right now we have tests for:-

- Functions( Get-version and FindCondaBinary ) 
- Client requests ( with and without multiple conda channels)
- Tests to verify installation of dependencies like ( conda , mamba , python , micromamba , restish )

**Comment by abhi18av** [comment]
@Aryan-sharma11  Sounds good 👍 

`restish` should not be a dependency for the server therefore, let's refactor to rely upon `Invoke-RestMethod` function from powershell.

**Comment by abhi18av** [comment]
Good work @Aryan-sharma11 - merging this PR now.

**Pull request merged**
