### PR TITLE
OpenApi spec

### PR DESCRIPTION
**Pull request by Aryan-sharma11**
Added OpenAPI specifications  https://github.com/biosharp-dotnet/sucuri-api/issues/11 and HTML response for base URL https://github.com/biosharp-dotnet/sucuri-api/issues/15

- The JSON response can be seen using  ` ../docs`
- It can be seen using API viewer using `../docs/view` 

Kindly, suggest what more can be improved in this.

### CODE REVIEW

**Comment by abhi18av** [comment]
Thanks for taking this forward @Aryan-sharma11 !

A tip regarding PR, if it can be explained better using a screenshot, please add it. 

image

**Review by abhi18av — CHANGES_REQUESTED** [review]
Good start 👍 

But a couple changes required before this can be merged.

Would appreciate a review/collaboration from @Mxrcon as well

**Comment by abhi18av** [comment]
@Aryan-sharma11 , is this PR ready to be merged?

**Comment by Aryan-sharma11** [comment]
> @Aryan-sharma11 , is this PR ready to be merged?

Changes that were  discussed are done, just waiting for review

**Review by Mxrcon — APPROVED** [review]
I've tested it locally and the issue with the circular `docs` part inside the documentation was removed as we discussed. I really liked the overall progress and the documentation should be good to go.

Good Job Aryan! You made a great work on this.

**Pull request merged**
