### PR TITLE
[Enhancement] Addition of  a health check endpoint

### LINKED ISSUE #16: [HOLD] Implement redirects for all paths which don't exist ( `/random` -> `/`)
HOLD:

I think that pode might actually do this by default.

### PR DESCRIPTION
**Pull request by Mxrcon**
:wave: Hey there, I took some time to study how endpoints work so I could gain some experience before working on a complex endpoint like the env solver. Creating a health endpoint seems to be a good way to pratice.

I Tried to Generate a Health endpoint to check if the API is active and working,
and this take us to one question: What is necessary for this api run?
1. Dependencies (Pode, powershell)
2. Conda distribution available on path

So if we could access the endpoint, of course that Pode and powershell are working.
But that doesn't mean that the api is "healthy", because we can get an API online
without a conda distribution available. 

That's why I based the health check on testing if there's a conda binary active and which is it's version, those 2 information should be enough for telling if the API is "Healthy" or "Ill". 

Additions:
1. new endpoint on `v1/health`
2. tests for the new endpoint
3. open api spec for the new endpoint

Example Request and it output:
```terminal
curl http://localhost:8085/v1/health
```
```json
{
"BinaryVersion":"0.24.0",
"CondaBinary":"micromamba"
}
```

I also took some time to test how pode works so I could redirect all requests from `/random` -> `/` as we discussed on #16, and I think that it worked.

Please, give it a try on your side!

Closes #16 

On my side those tests take less than 100 milliseconds, which looks very good.

I'd like to hear your thoughts on this one, before I work on new endpoints.

Kindly, Davi

### CODE REVIEW

**Comment by abhi18av** [comment]
Task linked: [CU-2wb0r1y Add a health check endpoint](https://app.clickup.com/t/2wb0r1y)

**Comment by Mxrcon** [comment]
I was thinking, maybe we should turn `FindCondaBinary` into a Public function as now it's a core function required by health endpoint as well as a sub function on `Get-VersionModule`.

What do you think about this promotion @abhi18av ? I don't think that this function should be private as it seems to be crucial for the good work of our API and will be used by almost all of our endpoints

**Comment by abhi18av** [comment]
Sure, it makes sense to promote the function and the change I'd requested is already implemented here https://github.com/biosharp-dotnet/sucuri-api/pull/34/commits/d923fc4a8c7cd19dda75437ec90690ace779adca so shall we merge this PR?

**Comment by Mxrcon** [comment]
Yes! let's squash and merge!

**Pull request merged**
